AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: CD Demo
Resources:
  CDDemo:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: lambda_function.handler
      Runtime: nodejs12.x
      CodeUri: ./LambdaCode
      Description: "Lambda Function node js for CD"
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam:392030919613:role/MyLambdaRole"
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /getazs
            Method: get
      Environment:
        Variables:
          REGION: ap-southeast-2